version: "3.8"

services:
  app:
    image: oven/bun:1
    working_dir: /app
    # In development: mount source, install, run migrations (retry), then start Next dev server
    command: sh -c "bun install && until bunx knex migrate:latest; do echo 'Waiting for DB to be ready...'; sleep 2; done && bunx next dev -H 0.0.0.0"
    volumes:
      - ./:/app:Z
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
      SKIP_ENV_VALIDATION: "1"
      DATABASE_CLIENT: pg
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      NEXT_TELEMETRY_DISABLED: "1"
      MAILER_PORT: "587"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z

volumes:
  pgdata:
